package com.fcms.controllers.policeOfficer;

import com.fcms.services.ParticipantService;
import com.fcms.services.BusinessException;
import com.fcms.models.Participant;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import java.net.URL;
import java.util.ResourceBundle;

public class AddParticipantController implements Initializable {

    @FXML private VBox validationError;
    @FXML private Label errorMessageLabel;
    @FXML private TextField nameField;
    @FXML private ComboBox<String> roleComboBox;
    @FXML private TextField contactField;
    @FXML private ComboBox<String> idTypeComboBox;
    @FXML private TextField idNumberField;
    @FXML private Button submitButton;
    @FXML private Button cancelButton;

    private ManageParticipantsController mainController;
    private ParticipantService participantService;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        this.participantService = new ParticipantService();
        setupComboBoxes();
    }

    private void setupComboBoxes() {
        ObservableList<String> roles = FXCollections.observableArrayList(
                "Suspect", "Victim", "Witness"
        );
        roleComboBox.setItems(roles);

        ObservableList<String> idTypes = FXCollections.observableArrayList(
                "Driver License", "Passport", "State ID", "National ID", "Other"
        );
        idTypeComboBox.setItems(idTypes);
    }

    public void setMainController(ManageParticipantsController mainController) {
        this.mainController = mainController;
    }

    @FXML
    private void handleSubmit() {
        if (!validateForm()) {
            return;
        }

        try {
            Participant newParticipant = createParticipant();
            participantService.addParticipant(newParticipant);

            if (mainController != null) {
                mainController.addNewParticipant(newParticipant);
            }

            closeWindow();
        } catch (BusinessException e) {
            showErrorAlert(e.getMessage());
        }
    }

    @FXML
    private void handleCancel() {
        closeWindow();
    }

    private boolean validateForm() {
        // UI validation only
        if (nameField.getText().isEmpty() ||
                roleComboBox.getValue() == null ||
                contactField.getText().isEmpty() ||
                idTypeComboBox.getValue() == null ||
                idNumberField.getText().isEmpty()) {

            showValidationError("All fields are required");
            return false;
        }

        clearValidationError();
        return true;
    }

    private Participant createParticipant() {
        return new Participant(
                null, // ID will be generated by service
                nameField.getText(),
                roleComboBox.getValue(),
                contactField.getText(),
                idTypeComboBox.getValue(),
                idNumberField.getText()
        );
    }

    private void showValidationError(String message) {
        errorMessageLabel.setText(message);
        validationError.setVisible(true);
    }

    private void clearValidationError() {
        validationError.setVisible(false);
    }

    private void showErrorAlert(String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle("Error");
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    private void closeWindow() {
        Stage stage = (Stage) cancelButton.getScene().getWindow();
        stage.close();
    }
}